server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${HOST_ADDR}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: ${HOST_ADDR}
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}

  mail:
    host: ${MAIL_HOST_ADDR}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

mybatis:
  type-aliases-package: com.kshrd.habittracker.model
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: ${SECRET_KEY}
    access-token-expiration-ms: ${EXPIRED_DURATION}

  otp:
    ttl-minutes: 5
    resend-cooldown-seconds: 60
    verify-max-attempts: 5
    verify-window-minutes: 10

s3:
  uri: ${S3_URI}
  accessKeyId: ${S3_ACCESS_KEY}
  secretAccessKey: ${S3_SECRET_KEY}